name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update apt database
        run: sudo apt-get update

      - name: Install mercurial
        run: sudo apt-get -y install mercurial

      - name: Install python
        run: sudo apt-get install curl python3 python3-pip

      - name: Install pkg-config
        run: sudo apt-get install pkg-config

      - name: Install libtool
        run: sudo apt-get install libtool

      - name: Configure mozconfig
        run: |
          echo -e "# Build only the JS shell\nac_add_options --enable-project=js\nac_add_options --enable-optimize\nac_add_options --prefix=/usr\nac_add_options --disable-debug\nmk_add_options MOZ_OBJDIR=@TOPSRCDIR@/obj-opt-@CONFIG_GUESS@" > .mozconfig
          export MOZCONFIG=.mozconfig

      - name: Bootstrap
        run: ./mach bootstrap --application-choice js

      - name: Clobber
        run: ./mach clobber

      - name: Build
        run: MOZCONFIG=.mozconfig ./mach build

      - name: Temp directory
        run: |
          mkdir temp
          cd temp/
          mkdir bin
          mkdir include
          mkdir lib
          cp ../obj-*/dist/bin/js bin/
          cp ../obj-*/js/src/build/js-config bin/
          cp -r ../obj-*/dist/include/** include/
          cp ../obj-*/dist/bin/lib*.so lib/
          mkdir lib/pkgconfig
          cp ../obj-*/js/src/build/js.pc lib/pkgconfig/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: obj
          path: temp/**

      - name: Upload artifacts - bin
        uses: actions/upload-artifact@v2
        with:
          name: bin
          path: temp/bin/**

      - name: Upload artifacts - include
        uses: actions/upload-artifact@v2
        with:
          name: include
          path: temp/include/**

      - name: Upload artifacts - lib
        uses: actions/upload-artifact@v2
        with:
          name: lib
          path: temp/lib/**
