name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update apt database
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get -y install mercurial curl python3 python3-pip pkg-config libtool

      - name: Configure
        run: |
          cd js/src/
          mkdir _build
          cd _build
          NIGHTLY_BUILD=1 ../configure --disable-jemalloc --with-system-zlib  --with-intl-api --disable-debug --enable-optimize --enable-jit  --prefix=/usr

      - name: Compile
        run: |
          cd js/src/_build/
          NIGHTLY_BUILD=1 make -j$(nproc)

      - name: Install
        run: |
          cd js/src/_build/
          DESTDIR=./_install make install
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: libmozjs
          path: js/src/_build/js/src/build/_install/usr/

      - uses: dev-drprasad/delete-tag-and-release@085c6969f18bad0de1b9f3fe6692a3cd01f64fe5
        with:
          delete_release: true
          tag_name: nightly
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Zip it
        run: |
          zip -r libmozjs js/src/_build/js/src/build/_install/usr/

      - name: Create the release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: Nightly Build ${{ steps.vars.outputs.sha_short }}
          draft: false
          prerelease: false
          files: |
            libmozjs.zip
