name: Builld
on:
  push:
  workflow_dispatch:

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update apt database
        run: sudo apt-get update

      - name: Install mercurial
        run: sudo apt-get -y install mercurial

      - name: Install python
        run: sudo apt-get install curl python3 python3-pip

      - name: Install pkg-config
        run: sudo apt-get install pkg-config

      - name: Configure mozconfig
        run: |
          mkdir mozconfigs
          echo -e "# Build only the JS shell\nac_add_options --enable-project=js\nac_add_options --enable-debug\nac_add_options --enable-optimize\nmk_add_options MOZ_OBJDIR=@TOPSRCDIR@/obj-debug-@CONFIG_GUESS@" > mozconfigs/debug
          export MOZCONFIG=mozconfigs/debug

      - name: Bootstrap
        run: MOZCONFIG=mozconfigs/debug ./mach bootstrap --application-choice js

      - name: Build
        run: MOZCONFIG=mozconfigs/debug ./mach build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: debug
          path: obj-debug-*
  build-optimized:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update apt database
        run: sudo apt-get update

      - name: Install mercurial
        run: sudo apt-get -y install mercurial

      - name: Install python
        run: sudo apt-get install curl python3 python3-pip

      - name: Install pkg-config
        run: sudo apt-get install pkg-config

      - name: Configure mozconfig
        run: |
          mkdir mozconfigs
          echo -e "# Build only the JS shell\nac_add_options --enable-project=js\nac_add_options --enable-optimize\nac_add_options --disable-debug\nmk_add_options MOZ_OBJDIR=@TOPSRCDIR@/obj-opt-@CONFIG_GUESS@" > mozconfigs/optimized
          export MOZCONFIG=mozconfigs/optimized

      - name: Bootstrap
        run: yes 5 | ./mach bootstrap --application-choice js

      - name: Build
        run: MOZCONFIG=mozconfigs/optimized ./mach build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: optimized
          path: obj-opt-*
