name: Upstream
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  upstream:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Update apt database
        run: sudo apt-get update

      - name: Install mercurial
        run: sudo apt-get -y install mercurial

      - name: Clone upstream
        run: hg clone https://hg.mozilla.org/mozilla-central mozilla-central

      - name: Move source to root
        run: |
          mv mozilla-central/* .
          rm -rf mozilla-central

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add files
        run: |
          git add -A
          git commit -am "Update upstream on $(date)"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
